version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/capmonster_python"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"